
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace IntelAgentWebApi.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class action_log
{

    public string Id { get; set; }

    public string sell_user_id { get; set; }

    public string buy_user_id { get; set; }

    public string stock_name_ { get; set; }

    public System.DateTime date_time { get; set; }

    public int quantity_ { get; set; }

    public double price_ { get; set; }

}

}
