//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelAgentWebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDataManager
    {
        public int Id { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string stock_name { get; set; }
        public Nullable<int> sell_action { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> limit { get; set; }
        public Nullable<int> market_limit { get; set; }
        public string strategy { get; set; }
        public string target { get; set; }
        public Nullable<int> carrying_amount { get; set; }
        public Nullable<int> price_check { get; set; }
    }
}
